title: Clipster
description: A home of the Clipster App
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
github:
  darwin_app_url: https://github.com/idroz/clipster/releases/download/latest/Clipster_Darwin_arm64.zip